### ISSUE TITLE
New Account Request

### ISSUE THREAD

**Issue by rukaury** [DIS-SIN/cloud-requests#5]
**On what platforms do you need an account?**

AWS is our standard Cloud platform. If selecting Azure or GCP, please provide reason below.

(Select an item by adding an `x` with the notation:  `[x]`)

- [x] AWS
- [ ] Azure
- [ ] GCP
- [ ] Slack
- [ ] Trello
- [ ] Zoom

**Other information**

**Comment by szinck1** [comment]
Please check your da-an email for a verification email.

**Comment by szinck1** [comment]
Aury confirmed he can access his account.
