### ISSUE TITLE
Account Created but Cannot be Seen

### ISSUE THREAD

**Issue by Moro-Code** [DIS-SIN/cloud-requests#7]
I created an account (Cortex) which starts with 6293278 which will be used to deploy all resources for the Cortex project

The account is stated as available in the Service Catalog. However, I'm not able to see it when logging into the single sign on and so unable to access it.

**Comment by szinck1** [comment]
There are two "Cortex" accounts created. One starts with 6 and the other with an 8.  The account that starts with 6 is assigned an email address that doesn't exist (typo), so I'm assuming you then created another account with the correct email?  

You should be able to see the "8" Cortex account now. Can I delete the other account?

**Comment by Moro-Code** [comment]
Yes I see the account now. Yup, please delete the other one.

Thanks Steven !
